import { Router } from "express";
import authRoutes from "../auth/routes/auth.route";
import adminRoutes from "../auth/routes/admin.routes";
import transactionRoutes from "../transaction/routes/transaction.routes";
import beneficiaryRoutes from "../transaction/routes/beneficiary.routes";
import fxRequestRoutes from "../transaction/routes/fx-request.routes";
import adminUserRoutes from "../admin/routes/user.routes";
import adminAccountRoutes from "../admin/routes/account.routes";
import adminTransactionRoutes from "../admin/routes/transaction.routes";
import adminAuditLogRoutes from "../admin/routes/audit-log.routes";
import adminCurrencyRoutes from "../admin/routes/currency.routes";
import adminExchangeRateRoutes from "../admin/routes/exchange-rate.routes";
import adminCurrencyReserveRoutes from "../admin/routes/currency-reserve.routes";
import adminApprovalRoutes from "../admin/routes/approval.routes";
import supportCustomerRoutes from "../support/routes/customer.routes";
import supportAccountRoutes from "../support/routes/account.routes";
import supportTransactionRoutes from "../support/routes/transaction.routes";
import supportOperationRoutes from "../support/routes/support-operation.routes";
import supportBeneficiaryRoutes from "../support/routes/beneficiary.routes";
import supportAuditLogRoutes from "../support/routes/audit-log.routes";
import auditorAuditLogRoutes from "../auditor/routes/audit-log.routes";
import auditorTransactionRoutes from "../auditor/routes/transaction.routes";
import auditorAccountRoutes from "../auditor/routes/account.routes";
import auditorApprovalRoutes from "../auditor/routes/approval-record.routes";
import auditorApprovalRecordRoutes from "../auditor/routes/approval-record.routes";
import auditorFxRequestRoutes from "../auditor/routes/fx-request.routes";
import userRoutes from "../user/routes/user.routes";
import accountRoutes from "../account/routes/account.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/admin", adminRoutes);
router.use("/transactions", transactionRoutes);
router.use("/beneficiaries", beneficiaryRoutes);
router.use("/fx-requests", fxRequestRoutes);
router.use("/admin/users", adminUserRoutes);
router.use("/admin/accounts", adminAccountRoutes);
router.use("/admin/transactions", adminTransactionRoutes);
router.use("/admin/audit-logs", adminAuditLogRoutes);
router.use("/admin/currencies", adminCurrencyRoutes);
router.use("/admin/exchange-rates", adminExchangeRateRoutes);
router.use("/admin/currency-reserves",adminCurrencyReserveRoutes,);
router.use("/admin/approvals", adminApprovalRoutes,);
router.use("/support/customers",supportCustomerRoutes,);
router.use("/support/customers/accounts",supportAccountRoutes,);
router.use("/support/customers",supportTransactionRoutes,);
router.use("/support/customers",supportOperationRoutes,);
router.use("/support/customers", supportBeneficiaryRoutes,);
router.use("/support/audit-logs",supportAuditLogRoutes,);
router.use("/auditor/audit-logs", auditorAuditLogRoutes,);
router.use("/auditor/transactions", auditorTransactionRoutes,);
router.use("/auditor/accounts", auditorAccountRoutes,); 
router.use("/auditor/approvals", auditorApprovalRoutes,); 
router.use("/auditor/approval-records", auditorApprovalRecordRoutes,); 
router.use("/auditor/fx-requests", auditorFxRequestRoutes,); 
router.use("/users", userRoutes);
router.use("/accounts", accountRoutes);

export default router;