export const ErrorCode = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  VALIDATION_ERROR: "VALIDATION_ERROR",

  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  NOT_FOUND: "NOT_FOUND",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  CONFLICT: "CONFLICT",

  BAD_REQUEST: "BAD_REQUEST",

  DATABASE_ERROR: "DATABASE_ERROR",
} as const;

export type ErrorCode =
  (typeof ErrorCode)[keyof typeof ErrorCode];